# Dockerfile
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the server script into the container
COPY server.py /app

# Command to run the server script
CMD ["python", "server.py"]
