apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp  # Specify namespace here
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: europe-west1-docker.pkg.dev/rare-phoenix-413915/my-repository/web-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
