version: 2.1
setup: true
parameters:
  base_image:
    type: string
    default: ubuntu-2204:2024.01.1
orbs:
  gcp-cli: circleci/gcp-cli@3.1.1
  shellcheck: circleci/shellcheck@3.2.0
  path-filter: circleci/path-filtering@1.0.0

commands:
  gcp-oidc-authenticate:
    description: "Authenticate with GCP using a CircleCI OIDC token."
    parameters:
      account_email:
        type: string
    steps:
      - run:
          name: "Create OIDC credential configuration"
          command: |
            # Store OIDC token in temp file
            export oidc_token_file_path="/home/circleci/oidc_token.json"
            export gcp_cred_config_file_path="/home/circleci/gcp_cred_config.json"
            export account_email="<< parameters.account_email >>"
            
            echo $CIRCLE_OIDC_TOKEN > $oidc_token_file_path
            # Create a credential configuration for the generated OIDC ID Token
            gcloud iam workload-identity-pools create-cred-config \
                "projects/869209469704/locations/global/workloadIdentityPools/ci-cd/providers/circleci-oidc"\
                --output-file="$gcp_cred_config_file_path" \
                --service-account="$account_email" \
                --credential-source-file=$oidc_token_file_path
                
            # Configure gcloud to leverage the generated credential configuration
            gcloud auth login --brief --cred-file "$gcp_cred_config_file_path"
            # Configure ADC
            echo "export GOOGLE_APPLICATION_CREDENTIALS='$gcp_cred_config_file_path'" | tee -a "$BASH_ENV"
            gcloud auth list
jobs:
  plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Plan
          command: |
            terraform init
            terraform plan
  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Apply
          command: |
            # terraform init
            # terraform apply -auto-approve
            echo "NEVER USE THIS"

  docker-build:
    parameters:
      platforms:
        description: Platforms to build for, comma-separated
        type: string
        default: "linux/amd64"
      resource_class:
        description: Docker resoruce class
        type: string
        default: medium
    machine:
      image: <<pipeline.parameters.base_image>>
      resource_class: "<<parameters.resource_class>>"
      docker_layer_caching: true  # we rely on this for faster builds, and actively warm it up for builds with common stages
    steps:
      - checkout
      - gcp-cli/install
      - gcp-oidc-authenticate:
          account_email: "ci-cd-writer@rare-phoenix-413915.iam.gserviceaccount.com"
      - run:
          name: Configure Docker to use Google Artifact Registry
          command: |
            gcloud auth list
            gcloud auth configure-docker europe-west1-docker.pkg.dev
      - run:
          name: Build Docker Image
          command: |
            docker build -t europe-west1-docker.pkg.dev/rare-phoenix-413915/my-repository/web-app-1:${CIRCLE_SHA1} ./docker/web-app --build-arg NUMBER="1"
            docker tag europe-west1-docker.pkg.dev/rare-phoenix-413915/my-repository/web-app-1:${CIRCLE_SHA1} europe-west1-docker.pkg.dev/rare-phoenix-413915/my-repository/web-app-1:latest
            docker push europe-west1-docker.pkg.dev/rare-phoenix-413915/my-repository/web-app-1:latest

            # docker build -t europe-west1-docker.pkg.dev/rare-phoenix-413915/my-repository/web-app-2:${CIRCLE_SHA1} ./docker/web-app --build-arg NUMBER="2"
            # docker tag europe-west1-docker.pkg.dev/rare-phoenix-413915/my-repository/web-app-2:${CIRCLE_SHA1} europe-west1-docker.pkg.dev/rare-phoenix-413915/my-repository/web-app-2:latest
            # docker push europe-west1-docker.pkg.dev/rare-phoenix-413915/my-repository/web-app-2:latest

            # docker build -t europe-west1-docker.pkg.dev/rare-phoenix-413915/my-repository/web-app-3:${CIRCLE_SHA1} ./docker/web-app --build-arg NUMBER="3" 
            # docker tag europe-west1-docker.pkg.dev/rare-phoenix-413915/my-repository/web-app-3:${CIRCLE_SHA1} europe-west1-docker.pkg.dev/rare-phoenix-413915/my-repository/web-app-3:latest
            # docker push europe-west1-docker.pkg.dev/rare-phoenix-413915/my-repository/web-app-3:latest


workflows:
  setup:
    jobs:
      - path-filtering/filter:
          name: filter-paths
          filters:
            branches:
              only: main
          mapping:
            tf_changes: &filter_tf
              paths:
                - "tf/**"
            docker_changes: &filter_docker
              paths:
                - "docker/**"
          base-revision: main
      - docker-build:
          requires:
            - filter-paths
          filters:
            branches:
              only: main
          when: *filter_docker
